extends:
  - airbnb
  - react-app
rules:
  react/jsx-indent: 
    - error
    - 4
  indent: 
    - error
    - 4
  jsx-a11y/label-has-associated-control:
    - error
    - required:
          - some:
            - nesting
            - id
